FROM squidfunk/mkdocs-material:latest
RUN pip install \
    mkdocs-git-revision-date-localized-plugin \
    mkdocs-awesome-nav \
    mkdocs-glightbox \
    mkdocs-table-reader-plugin \
    markdown-exec[ansi] \
