name: Generate RSS feed

on:
    schedule:
        - cron: "0 12 * * *"
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Setup Node
              uses: volta-cli/action@master
            - name: Generate RSS feed
              run: |
                  npm install --ignore-scripts
                  npm run tool:gen_rss
            - name: Commit
              run: |
                  if
                    git diff --quiet .
                  then
                    :
                  else
                    git config --global user.email hotarutwitter@gmail.com
                    git config --global user.name shimajiteppei
                    git add .
                    git commit -m "autogen rss feed"
                    git push origin main
                  fi
