name: Update Libraries

on:
    schedule:
        - cron: "0 11 * * THU"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Setup Node
              uses: volta-cli/action@master
            - name: Update package.json
              run: |
                  volta pin node@latest && volta pin npm@latest
                  npm install
                  npm run prepare
            - name: Build Artifact
              run: |
                  npm run build
            - name: Commit
              run: |
                  if
                    git diff --quiet package.json
                  then
                    :
                  else
                    git config --global user.email shimajiteppei@gmail.com
                    git config --global user.name shimajiteppei
                    git add package.json
                    git commit -m "update package.json"
                    git push origin main
                  fi
